### ISSUE TITLE
TypeError: utcoffset() got an unexpected keyword argument 'is_dst'

### ISSUE THREAD

**Issue by istvanp** [amonapp/amon#129]
This exception shows up after upgrading amonplus from 0.9.5 to 0.9.9.1 in System and Processes pages:

```
    Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/tornado-2.2-py2.6.egg/tornado/web.py", line 988, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/tornado-2.2-py2.6.egg/tornado/web.py", line 1739, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/amonplus-0.9.9.1-py2.6.egg/amonplus/web/apps/core/views.py", line 108, in get
    zone_difference = localtime_utc_timedelta()
  File "/usr/lib/python2.6/site-packages/amonplus-0.9.9.1-py2.6.egg/amonplus/utils/dates.py", line 20, in localtime_utc_timedelta
    td = local_timezone.utcoffset(naive_local_time, is_dst=is_dst)
TypeError: utcoffset() got an unexpected keyword argument 'is_dst'
```
